openapi: 3.0.0
info:
  title: Minha API REST
  version: 0.1
servers:
  - url: http://localhost:3000/
tags:
  - name: usuarios
paths:
  /usuarios:
    post:
      tags:
        - usuarios
      summary: Cria um novo usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - senha
              properties:
                email:
                  type: string
                senha:
                  type: string
      responses:
        '201':
          description: Usuário criado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
        '422':
          description: Erro de validação
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: Email e Senha são obrigatórios
components:
  schemas:
    Usuario:
      type: object
      properties:
        email:
          type: string
        senha:
          type: string
  schemas:
  securitySchemes:
